import = ["/home/alex/dotfiles/.config/alacritty/rose-pine.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "Fira Code Medium"
style = "Bold"

[font.bold_italic]
family = "Fira Code Medium"
style = "Bold Italic"

[font.italic]
family = "Fira Code Medium"
style = "Italic"

[font.normal]
family = "Fira Code Medium"
style = "Regular"

[window]
opacity = 0.85
startup_mode = "Maximized"
decorations = "None"

[window.padding]
x = 2
y = 2
